// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
				static class Vsix
				{
								public const string Id = "c080a549-e401-4431-9e65-3162096cc3f0";

                                public const string Name = "Insert Short Guid";
								public const string Description = @"Makes it super easy to insert a new GUID into any editor and input field";
								public const string Language = "en-US";
								public const string Version = "1.0";
								public const string Author = "Evan Chow";
								public const string Tags = "";
				}
}
